# Generated by Django 6.0.3 on 2026-03-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChronicleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('author_name', models.CharField(max_length=128)),
                ('author_handle', models.SlugField(max_length=64)),
                ('author_avatar_url', models.URLField(blank=True, max_length=500)),
                ('mood', models.CharField(blank=True, max_length=64)),
                ('mood_emoji', models.CharField(blank=True, max_length=24)),
                ('current_music', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_credit', models.CharField(blank=True, max_length=255)),
                ('display_likes', models.PositiveIntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='chronicle.chronicletag')),
            ],
            options={
                'ordering': ['-published_at', 'slug'],
            },
        ),
    ]
