# Generated by Django 6.0.3 on 2026-04-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicleentry',
            name='author_avatar_url',
            field=models.CharField(blank=True, help_text='Same-origin /media/… or https: URL.', max_length=500),
        ),
        migrations.AlterField(
            model_name='chronicleentry',
            name='image_url',
            field=models.CharField(blank=True, help_text='Same-origin /media/… or https: URL.', max_length=500),
        ),
    ]
