# Generated by Django 6.0.3 on 2026-03-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=255)),
                ('website_slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('topic', models.CharField(db_index=True, max_length=128)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['website_name'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_slug', models.SlugField(max_length=255)),
                ('page_slug', models.SlugField(default='home', max_length=255)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['site_slug', 'page_slug', 'id'],
            },
        ),
    ]
