import django.utils.timezone
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [("core", "0002_driftglassimage")]

    operations = [
        migrations.CreateModel(
            name="TerminusMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(db_index=True, max_length=128, unique=True)),
                ("sender_name", models.CharField(max_length=120)),
                ("message_type", models.CharField(choices=[("text", "Text"), ("email", "Email"), ("voice", "Voice Transcript")], default="text", max_length=16)),
                ("mood", models.CharField(choices=[("funny", "Funny"), ("heartbreaking", "Heartbreaking"), ("eerie", "Eerie"), ("calm", "Calm")], default="eerie", max_length=20)),
                ("subject_line", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField()),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-created_at"], "verbose_name": "Terminus message"},
        ),
        migrations.CreateModel(
            name="GiltEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(db_index=True, max_length=128, unique=True)),
                ("billionaire_name", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("mood_tag", models.CharField(blank=True, max_length=40)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("entry_date", models.DateField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-entry_date"], "verbose_name": "Gilt diary entry", "verbose_name_plural": "Gilt diary entries"},
        ),
        migrations.CreateModel(
            name="CollapseEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(db_index=True, max_length=128, unique=True)),
                ("timestamp_label", models.CharField(max_length=40)),
                ("source_type", models.CharField(choices=[("headline", "Headline"), ("slack", "Slack Leak"), ("memo", "Government Memo"), ("broadcast", "Broadcast")], default="headline", max_length=16)),
                ("source_label", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("sort_order", models.PositiveSmallIntegerField(db_index=True, default=0)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ["sort_order"], "verbose_name": "Collapse entry", "verbose_name_plural": "Collapse entries"},
        ),
        migrations.CreateModel(
            name="SomniumDream",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(db_index=True, max_length=128, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("narrative", models.TextField()),
                ("visual_description", models.TextField(blank=True)),
                ("analysis", models.TextField(blank=True)),
                ("dreamer_id", models.CharField(default="model-7b-nocturne", max_length=60)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-created_at"], "verbose_name": "Somnium dream"},
        ),
        migrations.CreateModel(
            name="ForkedTimeline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(db_index=True, max_length=128, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("premise", models.CharField(max_length=300)),
                ("divergence_year", models.PositiveSmallIntegerField(default=2000)),
                ("body", models.TextField()),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-created_at"], "verbose_name": "Forked timeline"},
        ),
        migrations.CreateModel(
            name="WhisperConfession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(db_index=True, max_length=128, unique=True)),
                ("body", models.TextField()),
                ("tone", models.CharField(choices=[("dark", "Dark"), ("funny", "Funny"), ("disturbing", "Disturbing"), ("bittersweet", "Bittersweet"), ("mundane", "Mundane")], default="dark", max_length=20)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("posted_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-posted_at"], "verbose_name": "Whisper confession"},
        ),
        migrations.CreateModel(
            name="EulogyPiece",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(db_index=True, max_length=128, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("archetype", models.CharField(max_length=120)),
                ("body", models.TextField()),
                ("still_breathing", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-created_at"], "verbose_name": "Eulogy piece"},
        ),
        migrations.CreateModel(
            name="ParlorDialogue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(db_index=True, max_length=128, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("person_a", models.CharField(max_length=120)),
                ("person_b", models.CharField(max_length=120)),
                ("body", models.TextField()),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-created_at"], "verbose_name": "Parlor dialogue"},
        ),
        migrations.CreateModel(
            name="EpochArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(db_index=True, max_length=128, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("artifact_type", models.CharField(choices=[("meme", "Meme"), ("language", "Language Fragment"), ("norm", "Cultural Norm"), ("site", "Website Remnant"), ("law", "Legal Text")], default="meme", max_length=16)),
                ("estimated_year", models.PositiveIntegerField(default=12026)),
                ("body", models.TextField()),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-created_at"], "verbose_name": "Epoch artifact"},
        ),
        migrations.CreateModel(
            name="IcarusStory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(db_index=True, max_length=128, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("excerpt", models.TextField()),
                ("body", models.TextField()),
                ("turning_point", models.CharField(blank=True, max_length=200)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-created_at"], "verbose_name": "Icarus story", "verbose_name_plural": "Icarus stories"},
        ),
        migrations.CreateModel(
            name="ParallaxSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(db_index=True, max_length=128, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("scenario", models.CharField(max_length=250)),
                ("body", models.TextField()),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-created_at"], "verbose_name": "Parallax snapshot"},
        ),
    ]
