# Generated by Django 6.0.3 on 2026-04-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_drop_deleted_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='codexentry',
            name='letter',
            field=models.CharField(blank=True, db_index=True, max_length=1),
        ),
        migrations.AddField(
            model_name='erratacorrection',
            name='fact_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='erratacorrection',
            name='wikipedia_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='residuefragment',
            name='wayback_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sabletheory',
            name='real_events',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sabletheory',
            name='wikipedia_urls',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staticsignal',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vestigeexhibit',
            name='wayback_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vestigeexhibit',
            name='wikipedia_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
