# Generated by Django 6.0.3 on 2026-04-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_enhance_site_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axiomlaw',
            name='civilization_name',
            field=models.CharField(help_text='Regulatory or standards source (e.g. EU AI Act, NIST AI RMF).', max_length=120, verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='axiomlaw',
            name='law_type',
            field=models.CharField(choices=[('constitution', 'Founding principle'), ('statute', 'Binding requirement'), ('ruling', 'Interpretive guidance'), ('amendment', 'Amendment / update')], max_length=20),
        ),
    ]
