# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_z_social_rename"),
    ]

    operations = [
        migrations.AddField(
            model_name="zprofile",
            name="followers_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="zprofile",
            name="following_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="zprofile",
            name="posts_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="repost_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-like_count", "-created_at"],
                name="core_post_like_cr_0b9f91_idx",
            ),
        ),
    ]
