# Generated by Django 6.0.3 on 2026-04-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_z_denorm_counts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='core_post_like_co_753663_idx',
            old_name='core_post_like_cr_0b9f91_idx',
        ),
    ]
