# Generated by Django 6.0.3 on 2026-04-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_core_post_like_cr_0b9f91_idx_core_post_like_co_753663_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_url',
            field=models.CharField(blank=True, help_text='Same-origin /media/… or https: URL.', max_length=500),
        ),
        migrations.AlterField(
            model_name='zprofile',
            name='avatar_url',
            field=models.CharField(blank=True, help_text='Same-origin /media/… or https: URL.', max_length=500),
        ),
        migrations.AlterField(
            model_name='zprofile',
            name='banner_url',
            field=models.CharField(blank=True, help_text='Same-origin /media/… or https: URL.', max_length=500),
        ),
    ]
