# Generated by Django 6.0.3 on 2026-04-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_media_url_path_friendly'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(db_index=True, help_text='Original article / page URL', max_length=2000, unique=True)),
                ('pool', models.CharField(db_index=True, help_text='Logical group from feeds.yaml (e.g. tech, fashion, longform, news, culture).', max_length=64)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(help_text='Plain extracted main text')),
                ('excerpt', models.TextField(blank=True)),
                ('author_line', models.CharField(blank=True, max_length=400)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('image_media_relpath', models.CharField(blank=True, max_length=500)),
                ('image_credit', models.CharField(blank=True, max_length=500)),
                ('content_hash', models.CharField(db_index=True, help_text='sha256 of normalized body for deduplication', max_length=64)),
                ('feed_label', models.CharField(blank=True, help_text='Source feed or file label (debugging only)', max_length=400)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_image_url', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'verbose_name': 'Ingested article',
                'verbose_name_plural': 'Ingested articles',
                'ordering': ['id'],
            },
        ),
    ]
