# Generated by Django 6.0.3 on 2026-03-30 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.SmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'Verso categories',
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='VersoArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=128)),
                ('published_at', models.DateField(db_index=True)),
                ('read_minutes', models.PositiveSmallIntegerField(default=8)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='verso.versocategory')),
            ],
            options={
                'ordering': ['-published_at', '-is_featured', 'slug'],
            },
        ),
    ]
