# Generated by Django 6.0.3 on 2026-03-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='versoarticle',
            name='image_credit',
            field=models.CharField(blank=True, help_text='Attribution line under the image.', max_length=255),
        ),
        migrations.AddField(
            model_name='versoarticle',
            name='image_url',
            field=models.URLField(blank=True, help_text='Hero image (HTTPS URL, e.g. Unsplash).', max_length=500),
        ),
    ]
