# Generated by Django 6.0.3 on 2026-04-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verso', '0002_versoarticle_image_credit_versoarticle_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versoarticle',
            name='image_url',
            field=models.CharField(blank=True, help_text='Hero image: same-origin /media/… URL, or any https: URL.', max_length=500),
        ),
    ]
